### ISSUE TITLE
str_replace_n does nor replace with greater than 1 character

### ISSUE THREAD

**Issue by akhst7** [martinctc/textworks#1]
Hi, 
I have been toying with str_replace_n to replace 3th occurrence of "/"  with more than two characters (e.g. "/%" in a following;
$`1`
```
/Downloads/GSE128423_RAW/GSM3674224_std1.barcodes.tsv.gz
/Downloads/GSE128423_RAW/GSM3674224_std1.genes.tsv.gz
/Downloads/GSE128423_RAW/GSM3674224_std1.matrix.mtx.gz
```

It works if the replacement is a single character as follows;

```
str_replace_nth(ld[[1]], "/", "%", 3)
/Downloads/GSE128423_RAW%GSM3674224_std1.barcodes.tsv.gz
/Downloads/GSE128423_RAW%GSM3674224_std1.genes.tsv.gz
/Downloads/GSE128423_RAW%GSM3674224_std1.matrix.mtx.gz
```

However,  
s```
tr_replace_nth(ld[[1]], "/", "/%", 3)
Downloads/GSE128423_RAW/GSM3674224_std1.barcodes.tsv.gz
/Downloads/GSE128423_RAW/GSM3674224_std1.genes.tsv.gz
Downloads/GSE128423_RAW/GSM3674224_std1.matrix.mtx.gz

```
Am I missing something here or this is a limitation of str_replace_n ?

**Comment by martinctc** [comment]
Hey @akhst7 - thanks for the issue. You are correct, this is actually a limitation of `str_replace_n()`. I'll see if I can push an update to fix this.

**Comment by martinctc** [comment]
Hey @akhst7 - this issue should be fixed. Please confirm if this is working for you, and I can close this issue. Thanks!

**Comment by akhst7** [comment]
@martinctc, It works !!  

Thanks.
